const controlClass = "w-full appearance-none rounded-lg border border-[#2a3550] bg-[#222e44] px-3 py-2.5 text-sm text-white transition-colors focus:border-[#C9A227] focus:outline-none";
const Field = ({ label, children }) => <div><label className="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-gray-300">{label}</label>{children}</div>;

export default function NewReportDrawer({ open, onClose }) {
  if (!open) return null;
  return <div className="fixed inset-0 z-50 flex justify-end"><button type="button" className="absolute inset-0 cursor-default bg-black/50" onClick={onClose} aria-label="Cerrar panel de nuevo reporte"/><div className="relative h-full w-full max-w-lg overflow-y-auto border-l border-[#2a3550] bg-[#141d2e]">
    <div className="sticky top-0 z-10 flex items-center justify-between border-b border-[#2a3550] bg-[#141d2e] px-4 py-4 sm:px-6"><h2 className="text-lg font-semibold">Nuevo reporte</h2><button type="button" onClick={onClose} className="h-8 w-8 rounded-lg text-gray-400 transition-colors hover:bg-[#1c2538] hover:text-white" aria-label="Cerrar">×</button></div>
    <div className="space-y-5 p-4 sm:p-6"><Field label="Nombre del reporte"><input placeholder="Ej. Ventas mensual Q2" className={controlClass}/></Field><Field label="Tipo de reporte"><select className={controlClass}>{["Ventas","Productos","Clientes","Financiero","Inventario"].map(value=><option key={value}>{value}</option>)}</select></Field><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field label="Fecha desde"><input type="date" className={controlClass}/></Field><Field label="Fecha hasta"><input type="date" className={controlClass}/></Field></div><Field label="Empresa"><select className={controlClass}><option>Todas las empresas</option><option>Grupo Víquez S.A</option><option>Textiles de Occidente</option><option>Pacific Pet Food</option></select></Field><Field label="Formato de exportación"><div className="grid grid-cols-3 gap-2">{["PDF","Excel","CSV"].map((format,index)=><button key={format} type="button" className={`cursor-pointer rounded-lg border py-2 text-sm font-medium ${index === 0 ? "border-[#C9A227]/30 bg-[#C9A227]/15 text-[#C9A227]" : "border-[#2a3550] bg-[#1c2538] text-gray-300 hover:bg-[#C9A227]/15 hover:text-white"}`}>{format}</button>)}</div></Field><div className="border-t border-[#2a3550] pt-4"><button type="button" className="w-full cursor-pointer rounded-lg bg-[#C9A227] py-2.5 text-sm font-medium text-white transition-colors hover:bg-[#B8921F]">Generar reporte</button></div></div>
  </div></div>;
}
