import { RiCalendarLine, RiCheckFill, RiDownloadFill, RiEyeFill, RiFilter3Fill, RiMoreFill, RiStarLine, RiTimeFill } from "react-icons/ri";
import { REPORT_STATUS_CONFIG, ReportsPagination, SAVED_REPORTS } from "./reportsViewData.jsx";

const controlClass = "w-full appearance-none rounded-lg border border-[#2a3550] bg-[#222e44] px-3 py-2 text-sm text-white transition-colors focus:border-[#C9A227] focus:outline-none";
const Field = ({ label, children }) => <div><label className="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-gray-300">{label}</label>{children}</div>;

function ReportsTable({ reports, currentPage, onPageChange }) {
  return <div className="min-w-0 flex-1"><div className="overflow-hidden rounded-xl border border-[#2a3550] bg-[#141d2e]">
    <div className="border-b border-[#2a3550] px-5 py-4"><h3 className="text-sm font-semibold">Reportes recientes</h3></div>
    <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-[#2a3550] text-xs uppercase tracking-wider text-gray-400">{["#", "Nombre del reporte", "Tipo de reporte", "Periodo", "Generado por", "Fecha de generación", "Estado", "Acciones"].map((heading) => <th key={heading} className={`px-5 py-3 font-medium ${heading === "Acciones" ? "text-right" : "text-left"}`}>{heading}</th>)}</tr></thead>
      <tbody>{reports.map((report) => { const status = REPORT_STATUS_CONFIG[report.status]; return <tr key={report.id} className="border-b border-[#2a3550] transition-colors last:border-0 hover:bg-[#1c2538]"><td className="px-5 py-3.5 font-mono text-xs text-gray-400">{report.number}</td><td className="px-5 py-3.5 font-medium text-white">{report.name}</td><td className="px-5 py-3.5 text-gray-300">{report.type}</td><td className="px-5 py-3.5 text-xs text-gray-300">{report.period}</td><td className="px-5 py-3.5 text-gray-300">{report.generatedBy}</td><td className="px-5 py-3.5 text-xs text-gray-400">{report.date}</td><td className="px-5 py-3.5"><span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-medium ${status.bg} ${status.text} ${status.border}`}>{report.status === "Completado" ? <RiCheckFill size={12} /> : <RiTimeFill size={12} />}{report.status}</span></td><td className="px-5 py-3.5"><div className="flex items-center justify-end gap-1">{[[RiDownloadFill,"Descargar"],[RiEyeFill,"Ver"],[RiMoreFill,"Más opciones"]].map(([Icon,title]) => <button key={title} type="button" title={title} className="flex h-7 w-7 cursor-pointer items-center justify-center rounded-lg text-gray-400 transition-colors hover:bg-[#C9A227]/15 hover:text-white"><Icon size={13} /></button>)}</div></td></tr>; })}</tbody>
    </table></div>
    <div className="flex items-center justify-between border-t border-[#2a3550] px-5 py-3"><span className="text-xs text-gray-400">Mostrando 1 a {reports.length} de 56 resultados</span><ReportsPagination current={currentPage} total={7} onChange={onPageChange} /></div>
  </div></div>;
}

function SavedReports() { return <div className="rounded-xl border border-[#2a3550] bg-[#141d2e] p-4"><h3 className="mb-3 text-sm font-semibold">Reportes guardados</h3><div className="space-y-2">{SAVED_REPORTS.map((report) => { const Icon=report.icon; return <div key={report.id} className="group flex cursor-pointer items-center gap-3 rounded-lg p-2 transition-colors hover:bg-[#1c2538]"><div className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-lg border border-[#2a3550] bg-[#1c2538] group-hover:border-[#C9A227]/50"><Icon size={14} style={{color:report.color}} /></div><span className="flex-1 text-sm text-gray-300">{report.name}</span><RiStarLine size={14} className="text-gray-500 transition-colors hover:text-[#C9A227]" /></div>; })}</div><button type="button" className="mt-3 w-full cursor-pointer py-2 text-center text-xs text-[#C9A227] transition-colors hover:text-white">Ver todos los reportes guardados</button></div>; }

function ReportsFilters({ search, status, type, includeTax, onSearchChange, onStatusChange, onTypeChange, onTaxChange, onClear }) {
  return <div className="space-y-4 xl:w-72 xl:flex-shrink-0"><div className="rounded-xl border border-[#2a3550] bg-[#141d2e] p-4"><div className="mb-4 flex items-center justify-between"><h3 className="flex items-center gap-2 text-sm font-semibold"><RiFilter3Fill size={14} className="text-[#C9A227]" /> Filtros</h3><button type="button" onClick={onClear} className="cursor-pointer text-xs text-gray-400 hover:text-white">Limpiar</button></div><div className="space-y-3">
    <Field label="Buscar"><input value={search} onChange={(e)=>onSearchChange(e.target.value)} placeholder="Nombre, código o usuario..." className={controlClass} /></Field>
    <Field label="Empresa"><select className={controlClass}><option>Todas las empresas</option><option>Grupo Víquez S.A</option><option>Textiles de Occidente</option><option>Pacific Pet Food</option></select></Field>
    <Field label="Sucursal"><select className={controlClass}><option>Todas las sucursales</option></select></Field>
    <Field label="Vendedor"><select className={controlClass}><option>Todos los vendedores</option><option>Ana Gómez</option><option>Manuel Rojas</option><option>Laura Gómez</option></select></Field>
    <div className="grid grid-cols-2 gap-2">{[["Fecha desde","01/06/2024"],["Fecha hasta","30/06/2024"]].map(([label,value])=><Field key={label} label={label}><div className="relative"><RiCalendarLine size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500"/><input defaultValue={value} className={`${controlClass} pl-8 pr-2`} /></div></Field>)}</div>
    <Field label="Tipo de reporte"><select value={type} onChange={(e)=>onTypeChange(e.target.value)} className={controlClass}>{["Todos","Ventas","Productos","Clientes","Financiero","Inventario"].map(value=><option key={value} value={value}>{value === "Todos" ? "Todos los reportes" : value}</option>)}</select></Field>
    <Field label="Estado"><select value={status} onChange={(e)=>onStatusChange(e.target.value)} className={controlClass}>{["Todos","Completado","En proceso"].map(value=><option key={value} value={value}>{value === "Todos" ? "Todos los estados" : value}</option>)}</select></Field>
    <Field label="Agrupar por"><select className={controlClass}>{["Día","Semana","Mes","Año"].map(value=><option key={value}>{value}</option>)}</select></Field>
    <div className="flex items-center justify-between py-2"><span className="text-sm text-gray-300">Incluir impuestos</span><button type="button" onClick={()=>onTaxChange(!includeTax)} className={`relative h-5 w-10 rounded-full transition-colors ${includeTax ? "bg-[#C9A227]" : "bg-gray-600"}`} aria-pressed={includeTax}><span className={`absolute top-0.5 h-4 w-4 rounded-full bg-white transition-transform ${includeTax ? "translate-x-5" : "translate-x-0.5"}`} /></button></div>
    <button type="button" className="w-full cursor-pointer rounded-lg bg-[#C9A227] py-2.5 text-sm font-medium text-white transition-colors hover:bg-[#B8921F]">Aplicar filtros</button>
  </div></div><SavedReports /></div>;
}

export default function ReportsWorkspace(props) { return <div className="flex flex-col gap-4 xl:flex-row"><ReportsTable reports={props.reports} currentPage={props.currentPage} onPageChange={props.onPageChange}/><ReportsFilters {...props}/></div>; }
