begin;

with country as (
  select country_id
  from public.countries
  where country_code = 'CR'
),
source_data (
  province_code,
  province_name,
  canton_code,
  canton_name,
  district_code,
  district_name
) as (
  values
  ('01', 'San José', '01', 'San José', '01', 'CARMEN'),
  ('01', 'San José', '01', 'San José', '02', 'MERCED'),
  ('01', 'San José', '01', 'San José', '03', 'HOSPITAL'),
  ('01', 'San José', '01', 'San José', '04', 'CATEDRAL'),
  ('01', 'San José', '01', 'San José', '05', 'ZAPOTE'),
  ('01', 'San José', '01', 'San José', '06', 'SAN FRANCISCO DE DOS RÍOS'),
  ('01', 'San José', '01', 'San José', '07', 'URUCA'),
  ('01', 'San José', '01', 'San José', '08', 'MATA REDONDA'),
  ('01', 'San José', '01', 'San José', '09', 'PAVAS'),
  ('01', 'San José', '01', 'San José', '10', 'HATILLO'),
  ('01', 'San José', '01', 'San José', '11', 'SAN SEBASTIÁN'),
  ('01', 'San José', '02', 'Escazú', '01', 'ESCAZÚ'),
  ('01', 'San José', '02', 'Escazú', '02', 'SAN ANTONIO'),
  ('01', 'San José', '02', 'Escazú', '03', 'SAN RAFAEL'),
  ('01', 'San José', '03', 'Desamparados', '01', 'DESAMPARADOS'),
  ('01', 'San José', '03', 'Desamparados', '02', 'SAN MIGUEL'),
  ('01', 'San José', '03', 'Desamparados', '03', 'SAN JUAN DE DIOS'),
  ('01', 'San José', '03', 'Desamparados', '04', 'SAN RAFAEL ARRIBA'),
  ('01', 'San José', '03', 'Desamparados', '05', 'SAN ANTONIO'),
  ('01', 'San José', '03', 'Desamparados', '06', 'FRAILES'),
  ('01', 'San José', '03', 'Desamparados', '07', 'PATARRÁ'),
  ('01', 'San José', '03', 'Desamparados', '08', 'SAN CRISTÓBAL'),
  ('01', 'San José', '03', 'Desamparados', '09', 'ROSARIO'),
  ('01', 'San José', '03', 'Desamparados', '10', 'DAMAS'),
  ('01', 'San José', '03', 'Desamparados', '11', 'SAN RAFAEL ABAJO'),
  ('01', 'San José', '03', 'Desamparados', '12', 'GRAVILIAS'),
  ('01', 'San José', '03', 'Desamparados', '13', 'LOS GUIDO'),
  ('01', 'San José', '04', 'Puriscal', '01', 'SANTIAGO'),
  ('01', 'San José', '04', 'Puriscal', '02', 'MERCEDES SUR'),
  ('01', 'San José', '04', 'Puriscal', '03', 'BARBACOAS'),
  ('01', 'San José', '04', 'Puriscal', '04', 'GRIFO ALTO'),
  ('01', 'San José', '04', 'Puriscal', '05', 'SAN RAFAEL'),
  ('01', 'San José', '04', 'Puriscal', '06', 'CANDELARITA'),
  ('01', 'San José', '04', 'Puriscal', '07', 'DESAMPARADITOS'),
  ('01', 'San José', '04', 'Puriscal', '08', 'SAN ANTONIO'),
  ('01', 'San José', '04', 'Puriscal', '09', 'CHIRES'),
  ('01', 'San José', '05', 'Tarrazú', '01', 'SAN MARCOS'),
  ('01', 'San José', '05', 'Tarrazú', '02', 'SAN LORENZO'),
  ('01', 'San José', '05', 'Tarrazú', '03', 'SAN CARLOS'),
  ('01', 'San José', '06', 'Aserrí', '01', 'ASERRI'),
  ('01', 'San José', '06', 'Aserrí', '02', 'TARBACA'),
  ('01', 'San José', '06', 'Aserrí', '03', 'VUELTA DE JORCO'),
  ('01', 'San José', '06', 'Aserrí', '04', 'SAN GABRIEL'),
  ('01', 'San José', '06', 'Aserrí', '05', 'LEGUA'),
  ('01', 'San José', '06', 'Aserrí', '06', 'MONTERREY'),
  ('01', 'San José', '06', 'Aserrí', '07', 'SALITRILLOS'),
  ('01', 'San José', '07', 'Mora', '01', 'COLÓN'),
  ('01', 'San José', '07', 'Mora', '02', 'GUAYABO'),
  ('01', 'San José', '07', 'Mora', '03', 'TABARCIA'),
  ('01', 'San José', '07', 'Mora', '04', 'PIEDRAS NEGRAS'),
  ('01', 'San José', '07', 'Mora', '05', 'PICAGRES'),
  ('01', 'San José', '07', 'Mora', '06', 'JARIS'),
  ('01', 'San José', '07', 'Mora', '07', 'QUITIRRISI'),
  ('01', 'San José', '08', 'Goicoechea', '01', 'GUADALUPE'),
  ('01', 'San José', '08', 'Goicoechea', '02', 'SAN FRANCISCO'),
  ('01', 'San José', '08', 'Goicoechea', '03', 'CALLE BLANCOS'),
  ('01', 'San José', '08', 'Goicoechea', '04', 'MATA DE PLÁTANO'),
  ('01', 'San José', '08', 'Goicoechea', '05', 'IPÍS'),
  ('01', 'San José', '08', 'Goicoechea', '06', 'RANCHO REDONDO'),
  ('01', 'San José', '08', 'Goicoechea', '07', 'PURRAL'),
  ('01', 'San José', '09', 'Santa Ana', '01', 'SANTA ANA'),
  ('01', 'San José', '09', 'Santa Ana', '02', 'SALITRAL'),
  ('01', 'San José', '09', 'Santa Ana', '03', 'POZOS'),
  ('01', 'San José', '09', 'Santa Ana', '04', 'URUCA'),
  ('01', 'San José', '09', 'Santa Ana', '05', 'PIEDADES'),
  ('01', 'San José', '09', 'Santa Ana', '06', 'BRASIL'),
  ('01', 'San José', '10', 'Alajuelita', '01', 'ALAJUELITA'),
  ('01', 'San José', '10', 'Alajuelita', '02', 'SAN JOSECITO'),
  ('01', 'San José', '10', 'Alajuelita', '03', 'SAN ANTONIO'),
  ('01', 'San José', '10', 'Alajuelita', '04', 'CONCEPCIÓN'),
  ('01', 'San José', '10', 'Alajuelita', '05', 'SAN FELIPE'),
  ('01', 'San José', '11', 'Vásquez de Coronado', '01', 'SAN ISIDRO'),
  ('01', 'San José', '11', 'Vásquez de Coronado', '02', 'SAN RAFAEL'),
  ('01', 'San José', '11', 'Vásquez de Coronado', '03', 'DULCE NOMBRE DE JESÚS'),
  ('01', 'San José', '11', 'Vásquez de Coronado', '04', 'PATALILLO'),
  ('01', 'San José', '11', 'Vásquez de Coronado', '05', 'CASCAJAL'),
  ('01', 'San José', '12', 'Acosta', '01', 'SAN IGNACIO'),
  ('01', 'San José', '12', 'Acosta', '02', 'GUAITIL Villa'),
  ('01', 'San José', '12', 'Acosta', '03', 'PALMICHAL'),
  ('01', 'San José', '12', 'Acosta', '04', 'CANGREJAL'),
  ('01', 'San José', '12', 'Acosta', '05', 'SABANILLAS'),
  ('01', 'San José', '13', 'Tibás', '01', 'SAN JUAN'),
  ('01', 'San José', '13', 'Tibás', '02', 'CINCO ESQUINAS'),
  ('01', 'San José', '13', 'Tibás', '03', 'ANSELMO LLORENTE'),
  ('01', 'San José', '13', 'Tibás', '04', 'LEON XIII'),
  ('01', 'San José', '13', 'Tibás', '05', 'COLIMA'),
  ('01', 'San José', '14', 'Moravia', '01', 'SAN VICENTE'),
  ('01', 'San José', '14', 'Moravia', '02', 'SAN JERÓNIMO'),
  ('01', 'San José', '14', 'Moravia', '03', 'LA TRINIDAD'),
  ('01', 'San José', '15', 'Montes de Oca', '01', 'SAN PEDRO'),
  ('01', 'San José', '15', 'Montes de Oca', '02', 'SABANILLA'),
  ('01', 'San José', '15', 'Montes de Oca', '03', 'MERCEDES'),
  ('01', 'San José', '15', 'Montes de Oca', '04', 'SAN RAFAEL'),
  ('01', 'San José', '16', 'Turrubares', '01', 'SAN PABLO'),
  ('01', 'San José', '16', 'Turrubares', '02', 'SAN PEDRO'),
  ('01', 'San José', '16', 'Turrubares', '03', 'SAN JUAN DE MATA'),
  ('01', 'San José', '16', 'Turrubares', '04', 'SAN LUIS'),
  ('01', 'San José', '16', 'Turrubares', '05', 'CARARA'),
  ('01', 'San José', '17', 'Dota', '01', 'SANTA MARÍA'),
  ('01', 'San José', '17', 'Dota', '02', 'JARDÍN'),
  ('01', 'San José', '17', 'Dota', '03', 'COPEY'),
  ('01', 'San José', '18', 'Curridabat', '01', 'CURRIDABAT'),
  ('01', 'San José', '18', 'Curridabat', '02', 'GRANADILLA'),
  ('01', 'San José', '18', 'Curridabat', '03', 'SÁNCHEZ'),
  ('01', 'San José', '18', 'Curridabat', '04', 'TIRRASES'),
  ('01', 'San José', '19', 'Pérez Zeledón', '01', 'SAN ISIDRO DE EL GENERAL'),
  ('01', 'San José', '19', 'Pérez Zeledón', '02', 'EL GENERAL'),
  ('01', 'San José', '19', 'Pérez Zeledón', '03', 'DANIEL FLORES'),
  ('01', 'San José', '19', 'Pérez Zeledón', '04', 'RIVAS'),
  ('01', 'San José', '19', 'Pérez Zeledón', '05', 'SAN PEDRO'),
  ('01', 'San José', '19', 'Pérez Zeledón', '06', 'PLATANARES'),
  ('01', 'San José', '19', 'Pérez Zeledón', '07', 'PEJIBAYE'),
  ('01', 'San José', '19', 'Pérez Zeledón', '08', 'CAJÓN'),
  ('01', 'San José', '19', 'Pérez Zeledón', '09', 'BARÚ'),
  ('01', 'San José', '19', 'Pérez Zeledón', '10', 'RÍO NUEVO'),
  ('01', 'San José', '19', 'Pérez Zeledón', '11', 'PÁRAMO'),
  ('01', 'San José', '20', 'León Cortéz Castro', '01', 'SAN PABLO'),
  ('01', 'San José', '20', 'León Cortéz Castro', '02', 'SAN ANDRÉS'),
  ('01', 'San José', '20', 'León Cortéz Castro', '03', 'LLANO BONITO'),
  ('01', 'San José', '20', 'León Cortéz Castro', '04', 'SAN ISIDRO'),
  ('01', 'San José', '20', 'León Cortéz Castro', '05', 'SANTA CRUZ'),
  ('01', 'San José', '20', 'León Cortéz Castro', '06', 'SAN ANTONIO'),
  ('02', 'Alajuela', '01', 'Alajuela', '01', 'ALAJUELA'),
  ('02', 'Alajuela', '01', 'Alajuela', '02', 'SAN JOSÉ'),
  ('02', 'Alajuela', '01', 'Alajuela', '03', 'CARRIZAL'),
  ('02', 'Alajuela', '01', 'Alajuela', '04', 'SAN ANTONIO'),
  ('02', 'Alajuela', '01', 'Alajuela', '05', 'GUÁCIMA'),
  ('02', 'Alajuela', '01', 'Alajuela', '06', 'SAN ISIDRO'),
  ('02', 'Alajuela', '01', 'Alajuela', '07', 'SABANILLA'),
  ('02', 'Alajuela', '01', 'Alajuela', '08', 'SAN RAFAEL'),
  ('02', 'Alajuela', '01', 'Alajuela', '09', 'RÍO SEGUNDO'),
  ('02', 'Alajuela', '01', 'Alajuela', '10', 'DESAMPARADOS'),
  ('02', 'Alajuela', '01', 'Alajuela', '11', 'TURRÚCARES'),
  ('02', 'Alajuela', '01', 'Alajuela', '12', 'TAMBOR'),
  ('02', 'Alajuela', '01', 'Alajuela', '13', 'GARITA'),
  ('02', 'Alajuela', '01', 'Alajuela', '14', 'SARAPIQUÍ'),
  ('02', 'Alajuela', '02', 'San Ramón', '01', 'SAN RAMÓN'),
  ('02', 'Alajuela', '02', 'San Ramón', '02', 'SANTIAGO'),
  ('02', 'Alajuela', '02', 'San Ramón', '03', 'SAN JUAN'),
  ('02', 'Alajuela', '02', 'San Ramón', '04', 'PIEDADES NORTE'),
  ('02', 'Alajuela', '02', 'San Ramón', '05', 'PIEDADES SUR'),
  ('02', 'Alajuela', '02', 'San Ramón', '06', 'SAN RAFAEL'),
  ('02', 'Alajuela', '02', 'San Ramón', '07', 'SAN ISIDRO'),
  ('02', 'Alajuela', '02', 'San Ramón', '08', 'ÁNGELES'),
  ('02', 'Alajuela', '02', 'San Ramón', '09', 'ALFARO'),
  ('02', 'Alajuela', '02', 'San Ramón', '10', 'VOLIO'),
  ('02', 'Alajuela', '02', 'San Ramón', '11', 'CONCEPCIÓN'),
  ('02', 'Alajuela', '02', 'San Ramón', '12', 'ZAPOTAL'),
  ('02', 'Alajuela', '02', 'San Ramón', '13', 'PEÑAS BLANCAS'),
  ('02', 'Alajuela', '03', 'Grecia', '01', 'GRECIA'),
  ('02', 'Alajuela', '03', 'Grecia', '02', 'SAN ISIDRO'),
  ('02', 'Alajuela', '03', 'Grecia', '03', 'SAN JOSÉ'),
  ('02', 'Alajuela', '03', 'Grecia', '04', 'SAN ROQUE'),
  ('02', 'Alajuela', '03', 'Grecia', '05', 'TACARES'),
  ('02', 'Alajuela', '03', 'Grecia', '06', 'RÍO CUARTO'),
  ('02', 'Alajuela', '03', 'Grecia', '07', 'PUENTE DE PIEDRA'),
  ('02', 'Alajuela', '03', 'Grecia', '08', 'BOLÍVAR'),
  ('02', 'Alajuela', '04', 'San Mateo', '01', 'SAN MATEO'),
  ('02', 'Alajuela', '04', 'San Mateo', '02', 'DESMONTE'),
  ('02', 'Alajuela', '04', 'San Mateo', '03', 'JESÚS MARÍA'),
  ('02', 'Alajuela', '04', 'San Mateo', '04', 'LABRADOR'),
  ('02', 'Alajuela', '05', 'Atenas', '01', 'ATENAS'),
  ('02', 'Alajuela', '05', 'Atenas', '02', 'JESÚS'),
  ('02', 'Alajuela', '05', 'Atenas', '03', 'MERCEDES'),
  ('02', 'Alajuela', '05', 'Atenas', '04', 'SAN ISIDRO'),
  ('02', 'Alajuela', '05', 'Atenas', '05', 'CONCEPCIÓN'),
  ('02', 'Alajuela', '05', 'Atenas', '06', 'SAN JOSE'),
  ('02', 'Alajuela', '05', 'Atenas', '07', 'SANTA EULALIA'),
  ('02', 'Alajuela', '05', 'Atenas', '08', 'ESCOBAL'),
  ('02', 'Alajuela', '06', 'Naranjo', '01', 'NARANJO'),
  ('02', 'Alajuela', '06', 'Naranjo', '02', 'SAN MIGUEL'),
  ('02', 'Alajuela', '06', 'Naranjo', '03', 'SAN JOSÉ'),
  ('02', 'Alajuela', '06', 'Naranjo', '04', 'CIRRÍ SUR'),
  ('02', 'Alajuela', '06', 'Naranjo', '05', 'SAN JERÓNIMO'),
  ('02', 'Alajuela', '06', 'Naranjo', '06', 'SAN JUAN'),
  ('02', 'Alajuela', '06', 'Naranjo', '07', 'EL ROSARIO'),
  ('02', 'Alajuela', '06', 'Naranjo', '08', 'PALMITOS'),
  ('02', 'Alajuela', '07', 'Palmares', '01', 'PALMARES'),
  ('02', 'Alajuela', '07', 'Palmares', '02', 'ZARAGOZA'),
  ('02', 'Alajuela', '07', 'Palmares', '03', 'BUENOS AIRES'),
  ('02', 'Alajuela', '07', 'Palmares', '04', 'SANTIAGO'),
  ('02', 'Alajuela', '07', 'Palmares', '05', 'CANDELARIA'),
  ('02', 'Alajuela', '07', 'Palmares', '06', 'ESQUÍPULAS'),
  ('02', 'Alajuela', '07', 'Palmares', '07', 'LA GRANJA'),
  ('02', 'Alajuela', '08', 'Poás', '01', 'SAN PEDRO'),
  ('02', 'Alajuela', '08', 'Poás', '02', 'SAN JUAN'),
  ('02', 'Alajuela', '08', 'Poás', '03', 'SAN RAFAEL'),
  ('02', 'Alajuela', '08', 'Poás', '04', 'CARRILLOS'),
  ('02', 'Alajuela', '08', 'Poás', '05', 'SABANA REDONDA'),
  ('02', 'Alajuela', '09', 'Orotina', '01', 'OROTINA'),
  ('02', 'Alajuela', '09', 'Orotina', '02', 'EL MASTATE'),
  ('02', 'Alajuela', '09', 'Orotina', '03', 'HACIENDA VIEJA'),
  ('02', 'Alajuela', '09', 'Orotina', '04', 'COYOLAR'),
  ('02', 'Alajuela', '09', 'Orotina', '05', 'LA CEIBA'),
  ('02', 'Alajuela', '10', 'San Carlos', '01', 'QUESADA'),
  ('02', 'Alajuela', '10', 'San Carlos', '02', 'FLORENCIA'),
  ('02', 'Alajuela', '10', 'San Carlos', '03', 'BUENAVISTA'),
  ('02', 'Alajuela', '10', 'San Carlos', '04', 'AGUAS ZARCAS'),
  ('02', 'Alajuela', '10', 'San Carlos', '05', 'VENECIA'),
  ('02', 'Alajuela', '10', 'San Carlos', '06', 'PITAL'),
  ('02', 'Alajuela', '10', 'San Carlos', '07', 'LA FORTUNA'),
  ('02', 'Alajuela', '10', 'San Carlos', '08', 'LA TIGRA'),
  ('02', 'Alajuela', '10', 'San Carlos', '09', 'LA PALMERA'),
  ('02', 'Alajuela', '10', 'San Carlos', '10', 'VENADO'),
  ('02', 'Alajuela', '10', 'San Carlos', '11', 'CUTRIS'),
  ('02', 'Alajuela', '10', 'San Carlos', '12', 'MONTERREY'),
  ('02', 'Alajuela', '10', 'San Carlos', '13', 'POCOSOL'),
  ('02', 'Alajuela', '11', 'Zarcero', '01', 'ZARCERO'),
  ('02', 'Alajuela', '11', 'Zarcero', '02', 'LAGUNA'),
  ('02', 'Alajuela', '11', 'Zarcero', '04', 'GUADALUPE'),
  ('02', 'Alajuela', '11', 'Zarcero', '05', 'PALMIRA'),
  ('02', 'Alajuela', '11', 'Zarcero', '06', 'ZAPOTE'),
  ('02', 'Alajuela', '11', 'Zarcero', '07', 'BRISAS'),
  ('02', 'Alajuela', '12', 'Valverde Vega', '01', 'SARCHÍ NORTE'),
  ('02', 'Alajuela', '12', 'Valverde Vega', '02', 'SARCHÍ SUR'),
  ('02', 'Alajuela', '12', 'Valverde Vega', '03', 'TORO AMARILLO'),
  ('02', 'Alajuela', '12', 'Valverde Vega', '04', 'SAN PEDRO'),
  ('02', 'Alajuela', '12', 'Valverde Vega', '05', 'RODRÍGUEZ'),
  ('02', 'Alajuela', '13', 'Upala', '01', 'UPALA'),
  ('02', 'Alajuela', '13', 'Upala', '02', 'AGUAS CLARAS'),
  ('02', 'Alajuela', '13', 'Upala', '03', 'SAN JOSÉ o PIZOTE'),
  ('02', 'Alajuela', '13', 'Upala', '04', 'BIJAGUA'),
  ('02', 'Alajuela', '13', 'Upala', '05', 'DELICIAS'),
  ('02', 'Alajuela', '13', 'Upala', '06', 'DOS RÍOS'),
  ('02', 'Alajuela', '13', 'Upala', '07', 'YOLILLAL'),
  ('02', 'Alajuela', '13', 'Upala', '08', 'CANALETE'),
  ('02', 'Alajuela', '14', 'Los Chiles', '01', 'LOS CHILES'),
  ('02', 'Alajuela', '14', 'Los Chiles', '02', 'CAÑO NEGRO'),
  ('02', 'Alajuela', '14', 'Los Chiles', '03', 'EL AMPARO'),
  ('02', 'Alajuela', '14', 'Los Chiles', '04', 'SAN JORGE'),
  ('02', 'Alajuela', '15', 'Guatuso', '02', 'BUENAVISTA'),
  ('02', 'Alajuela', '15', 'Guatuso', '03', 'COTE'),
  ('02', 'Alajuela', '15', 'Guatuso', '04', 'KATIRA'),
  ('03', 'Cartago', '01', 'Cartago', '01', 'ORIENTAL'),
  ('03', 'Cartago', '01', 'Cartago', '02', 'OCCIDENTAL'),
  ('03', 'Cartago', '01', 'Cartago', '03', 'CARMEN'),
  ('03', 'Cartago', '01', 'Cartago', '04', 'SAN NICOLÁS'),
  ('03', 'Cartago', '01', 'Cartago', '05', 'AGUACALIENTE o SAN FRANCISCO'),
  ('03', 'Cartago', '01', 'Cartago', '06', 'GUADALUPE o ARENILLA'),
  ('03', 'Cartago', '01', 'Cartago', '07', 'CORRALILLO'),
  ('03', 'Cartago', '01', 'Cartago', '08', 'TIERRA BLANCA'),
  ('03', 'Cartago', '01', 'Cartago', '09', 'DULCE NOMBRE'),
  ('03', 'Cartago', '01', 'Cartago', '10', 'LLANO GRANDE'),
  ('03', 'Cartago', '01', 'Cartago', '11', 'QUEBRADILLA'),
  ('03', 'Cartago', '02', 'Paraíso', '01', 'PARAÍSO'),
  ('03', 'Cartago', '02', 'Paraíso', '02', 'SANTIAGO'),
  ('03', 'Cartago', '02', 'Paraíso', '03', 'OROSI'),
  ('03', 'Cartago', '02', 'Paraíso', '04', 'CACHÍ'),
  ('03', 'Cartago', '02', 'Paraíso', '05', 'LLANOS DE SANTA LUCÍA'),
  ('03', 'Cartago', '03', 'La Unión', '01', 'TRES RÍOS'),
  ('03', 'Cartago', '03', 'La Unión', '02', 'SAN DIEGO'),
  ('03', 'Cartago', '03', 'La Unión', '03', 'SAN JUAN'),
  ('03', 'Cartago', '03', 'La Unión', '04', 'SAN RAFAEL'),
  ('03', 'Cartago', '03', 'La Unión', '05', 'CONCEPCIÓN'),
  ('03', 'Cartago', '03', 'La Unión', '06', 'DULCE NOMBRE'),
  ('03', 'Cartago', '03', 'La Unión', '07', 'SAN RAMÓN'),
  ('03', 'Cartago', '03', 'La Unión', '08', 'RÍO AZUL'),
  ('03', 'Cartago', '04', 'Jiménez', '01', 'JUAN VIÑAS'),
  ('03', 'Cartago', '04', 'Jiménez', '02', 'TUCURRIQUE'),
  ('03', 'Cartago', '04', 'Jiménez', '03', 'PEJIBAYE'),
  ('03', 'Cartago', '05', 'Turrialba', '01', 'TURRIALBA'),
  ('03', 'Cartago', '05', 'Turrialba', '02', 'LA SUIZA'),
  ('03', 'Cartago', '05', 'Turrialba', '03', 'PERALTA'),
  ('03', 'Cartago', '05', 'Turrialba', '04', 'SANTA CRUZ'),
  ('03', 'Cartago', '05', 'Turrialba', '05', 'SANTA TERESITA'),
  ('03', 'Cartago', '05', 'Turrialba', '06', 'PAVONES'),
  ('03', 'Cartago', '05', 'Turrialba', '07', 'TUIS'),
  ('03', 'Cartago', '05', 'Turrialba', '08', 'TAYUTIC'),
  ('03', 'Cartago', '05', 'Turrialba', '09', 'SANTA ROSA'),
  ('03', 'Cartago', '05', 'Turrialba', '10', 'TRES EQUIS'),
  ('03', 'Cartago', '05', 'Turrialba', '11', 'LA ISABEL'),
  ('03', 'Cartago', '05', 'Turrialba', '12', 'CHIRRIPÓ'),
  ('03', 'Cartago', '06', 'Alvarado', '01', 'PACAYAS'),
  ('03', 'Cartago', '06', 'Alvarado', '02', 'CERVANTES'),
  ('03', 'Cartago', '06', 'Alvarado', '03', 'CAPELLADES'),
  ('03', 'Cartago', '07', 'Oreamuno', '01', 'SAN RAFAEL'),
  ('03', 'Cartago', '07', 'Oreamuno', '02', 'COT'),
  ('03', 'Cartago', '07', 'Oreamuno', '03', 'POTRERO CERRADO'),
  ('03', 'Cartago', '07', 'Oreamuno', '04', 'CIPRESES'),
  ('03', 'Cartago', '07', 'Oreamuno', '05', 'SANTA ROSA'),
  ('03', 'Cartago', '08', 'El Guarco', '01', 'EL TEJAR'),
  ('03', 'Cartago', '08', 'El Guarco', '02', 'SAN ISIDRO'),
  ('03', 'Cartago', '08', 'El Guarco', '03', 'TOBOSI'),
  ('03', 'Cartago', '08', 'El Guarco', '04', 'PATIO DE AGUA'),
  ('04', 'Heredia', '01', 'Heredia', '01', 'HEREDIA'),
  ('04', 'Heredia', '01', 'Heredia', '02', 'MERCEDES'),
  ('04', 'Heredia', '01', 'Heredia', '03', 'SAN FRANCISCO'),
  ('04', 'Heredia', '01', 'Heredia', '04', 'ULLOA'),
  ('04', 'Heredia', '01', 'Heredia', '05', 'VARABLANCA'),
  ('04', 'Heredia', '02', 'Barva', '01', 'BARVA'),
  ('04', 'Heredia', '02', 'Barva', '02', 'SAN PEDRO'),
  ('04', 'Heredia', '02', 'Barva', '03', 'SAN PABLO'),
  ('04', 'Heredia', '02', 'Barva', '04', 'SAN ROQUE'),
  ('04', 'Heredia', '02', 'Barva', '05', 'SANTA LUCÍA'),
  ('04', 'Heredia', '02', 'Barva', '06', 'SAN JOSÉ DE LA MONTAÑA'),
  ('04', 'Heredia', '03', 'Santo Domingo', '02', 'SAN VICENTE'),
  ('04', 'Heredia', '03', 'Santo Domingo', '03', 'SAN MIGUEL'),
  ('04', 'Heredia', '03', 'Santo Domingo', '04', 'PARACITO'),
  ('04', 'Heredia', '03', 'Santo Domingo', '05', 'SANTO TOMÁS'),
  ('04', 'Heredia', '03', 'Santo Domingo', '06', 'SANTA ROSA'),
  ('04', 'Heredia', '03', 'Santo Domingo', '07', 'TURES'),
  ('04', 'Heredia', '03', 'Santo Domingo', '08', 'PARÁ'),
  ('04', 'Heredia', '04', 'Santa Bárbara', '01', 'SANTA BÁRBARA'),
  ('04', 'Heredia', '04', 'Santa Bárbara', '02', 'SAN PEDRO'),
  ('04', 'Heredia', '04', 'Santa Bárbara', '03', 'SAN JUAN'),
  ('04', 'Heredia', '04', 'Santa Bárbara', '04', 'JESÚS'),
  ('04', 'Heredia', '04', 'Santa Bárbara', '05', 'SANTO DOMINGO'),
  ('04', 'Heredia', '04', 'Santa Bárbara', '06', 'PURABÁ'),
  ('04', 'Heredia', '05', 'San Rafaél', '01', 'SAN RAFAEL'),
  ('04', 'Heredia', '05', 'San Rafaél', '02', 'SAN JOSECITO'),
  ('04', 'Heredia', '05', 'San Rafaél', '03', 'SANTIAGO'),
  ('04', 'Heredia', '05', 'San Rafaél', '04', 'ÁNGELES'),
  ('04', 'Heredia', '05', 'San Rafaél', '05', 'CONCEPCIÓN'),
  ('04', 'Heredia', '06', 'San Isidro', '01', 'SAN ISIDRO'),
  ('04', 'Heredia', '06', 'San Isidro', '02', 'SAN JOSÉ'),
  ('04', 'Heredia', '06', 'San Isidro', '03', 'CONCEPCIÓN'),
  ('04', 'Heredia', '06', 'San Isidro', '04', 'SAN FRANCISCO'),
  ('04', 'Heredia', '07', 'Belén', '01', 'SAN ANTONIO'),
  ('04', 'Heredia', '07', 'Belén', '02', 'LA RIBERA'),
  ('04', 'Heredia', '07', 'Belén', '03', 'LA ASUNCIÓN'),
  ('04', 'Heredia', '08', 'Flores', '01', 'SAN JOAQUÍN'),
  ('04', 'Heredia', '08', 'Flores', '02', 'BARRANTES'),
  ('04', 'Heredia', '08', 'Flores', '03', 'LLORENTE'),
  ('04', 'Heredia', '09', 'San Pablo', '01', 'SAN PABLO'),
  ('04', 'Heredia', '10', 'Sarapiquí', '01', 'PUERTO VIEJO'),
  ('04', 'Heredia', '10', 'Sarapiquí', '02', 'LA VIRGEN'),
  ('04', 'Heredia', '10', 'Sarapiquí', '03', 'LAS HORQUETAS'),
  ('04', 'Heredia', '10', 'Sarapiquí', '04', 'LLANURAS DEL GASPAR'),
  ('04', 'Heredia', '10', 'Sarapiquí', '05', 'CUREÑA'),
  ('05', 'Guanacaste', '01', 'Liberia', '01', 'LIBERIA'),
  ('05', 'Guanacaste', '01', 'Liberia', '02', 'CAÑAS DULCES'),
  ('05', 'Guanacaste', '01', 'Liberia', '03', 'MAYORGA'),
  ('05', 'Guanacaste', '01', 'Liberia', '04', 'NACASCOLO'),
  ('05', 'Guanacaste', '01', 'Liberia', '05', 'CURUBANDÉ'),
  ('05', 'Guanacaste', '02', 'Nicoya', '01', 'NICOYA'),
  ('05', 'Guanacaste', '02', 'Nicoya', '02', 'MANSIÓN'),
  ('05', 'Guanacaste', '02', 'Nicoya', '03', 'SAN ANTONIO'),
  ('05', 'Guanacaste', '02', 'Nicoya', '04', 'QUEBRADA HONDA'),
  ('05', 'Guanacaste', '02', 'Nicoya', '05', 'SÁMARA'),
  ('05', 'Guanacaste', '02', 'Nicoya', '06', 'NOSARA'),
  ('05', 'Guanacaste', '02', 'Nicoya', '07', 'BELÉN DE NOSARITA'),
  ('05', 'Guanacaste', '03', 'Santa Cruz', '01', 'SANTA CRUZ'),
  ('05', 'Guanacaste', '03', 'Santa Cruz', '02', 'BOLSÓN'),
  ('05', 'Guanacaste', '03', 'Santa Cruz', '03', 'VEINTISIETE DE ABRIL'),
  ('05', 'Guanacaste', '03', 'Santa Cruz', '04', 'TEMPATE'),
  ('05', 'Guanacaste', '03', 'Santa Cruz', '05', 'CARTAGENA'),
  ('05', 'Guanacaste', '03', 'Santa Cruz', '06', 'CUAJINIQUIL'),
  ('05', 'Guanacaste', '03', 'Santa Cruz', '07', 'DIRIÁ'),
  ('05', 'Guanacaste', '03', 'Santa Cruz', '08', 'CABO VELAS'),
  ('05', 'Guanacaste', '03', 'Santa Cruz', '09', 'TAMARINDO'),
  ('05', 'Guanacaste', '04', 'Bagaces', '01', 'BAGACES'),
  ('05', 'Guanacaste', '04', 'Bagaces', '02', 'LA FORTUNA'),
  ('05', 'Guanacaste', '04', 'Bagaces', '03', 'MOGOTE'),
  ('05', 'Guanacaste', '04', 'Bagaces', '04', 'RÍO NARANJO'),
  ('05', 'Guanacaste', '05', 'Carrillo', '01', 'FILADELFIA'),
  ('05', 'Guanacaste', '05', 'Carrillo', '02', 'PALMIRA'),
  ('05', 'Guanacaste', '05', 'Carrillo', '03', 'SARDINAL'),
  ('05', 'Guanacaste', '05', 'Carrillo', '04', 'BELÉN'),
  ('05', 'Guanacaste', '06', 'Cañas', '01', 'CAÑAS'),
  ('05', 'Guanacaste', '06', 'Cañas', '02', 'PALMIRA'),
  ('05', 'Guanacaste', '06', 'Cañas', '03', 'SAN MIGUEL'),
  ('05', 'Guanacaste', '06', 'Cañas', '04', 'BEBEDERO'),
  ('05', 'Guanacaste', '06', 'Cañas', '05', 'POROZAL'),
  ('05', 'Guanacaste', '07', 'Abangáres', '01', 'LAS JUNTAS'),
  ('05', 'Guanacaste', '07', 'Abangáres', '02', 'SIERRA'),
  ('05', 'Guanacaste', '07', 'Abangáres', '03', 'SAN JUAN'),
  ('05', 'Guanacaste', '07', 'Abangáres', '04', 'COLORADO'),
  ('05', 'Guanacaste', '08', 'Tilarán', '01', 'TILARÁN'),
  ('05', 'Guanacaste', '08', 'Tilarán', '02', 'QUEBRADA GRANDE'),
  ('05', 'Guanacaste', '08', 'Tilarán', '03', 'TRONADORA'),
  ('05', 'Guanacaste', '08', 'Tilarán', '04', 'SANTA ROSA'),
  ('05', 'Guanacaste', '08', 'Tilarán', '05', 'LÍBANO'),
  ('05', 'Guanacaste', '08', 'Tilarán', '06', 'TIERRAS MORENAS'),
  ('05', 'Guanacaste', '08', 'Tilarán', '07', 'ARENAL'),
  ('05', 'Guanacaste', '09', 'Nandayure', '01', 'CARMONA'),
  ('05', 'Guanacaste', '09', 'Nandayure', '02', 'SANTA RITA'),
  ('05', 'Guanacaste', '09', 'Nandayure', '03', 'ZAPOTAL'),
  ('05', 'Guanacaste', '09', 'Nandayure', '04', 'SAN PABLO'),
  ('05', 'Guanacaste', '09', 'Nandayure', '05', 'PORVENIR'),
  ('05', 'Guanacaste', '09', 'Nandayure', '06', 'BEJUCO'),
  ('05', 'Guanacaste', '10', 'La Cruz', '01', 'LA CRUZ'),
  ('05', 'Guanacaste', '10', 'La Cruz', '02', 'SANTA CECILIA'),
  ('05', 'Guanacaste', '10', 'La Cruz', '03', 'LA GARITA'),
  ('05', 'Guanacaste', '10', 'La Cruz', '04', 'SANTA ELENA'),
  ('05', 'Guanacaste', '11', 'Hojancha', '01', 'HOJANCHA'),
  ('05', 'Guanacaste', '11', 'Hojancha', '02', 'MONTE ROMO'),
  ('05', 'Guanacaste', '11', 'Hojancha', '03', 'PUERTO CARRILLO'),
  ('05', 'Guanacaste', '11', 'Hojancha', '04', 'HUACAS'),
  ('06', 'Puntarenas', '01', 'Puntarenas', '01', 'PUNTARENAS'),
  ('06', 'Puntarenas', '01', 'Puntarenas', '02', 'PITAHAYA'),
  ('06', 'Puntarenas', '01', 'Puntarenas', '03', 'CHOMES'),
  ('06', 'Puntarenas', '01', 'Puntarenas', '04', 'LEPANTO'),
  ('06', 'Puntarenas', '01', 'Puntarenas', '05', 'PAQUERA'),
  ('06', 'Puntarenas', '01', 'Puntarenas', '06', 'MANZANILLO'),
  ('06', 'Puntarenas', '01', 'Puntarenas', '07', 'GUACIMAL'),
  ('06', 'Puntarenas', '01', 'Puntarenas', '08', 'BARRANCA'),
  ('06', 'Puntarenas', '01', 'Puntarenas', '09', 'MONTE VERDE'),
  ('06', 'Puntarenas', '01', 'Puntarenas', '11', 'CÓBANO'),
  ('06', 'Puntarenas', '01', 'Puntarenas', '12', 'CHACARITA'),
  ('06', 'Puntarenas', '01', 'Puntarenas', '13', 'CHIRA'),
  ('06', 'Puntarenas', '01', 'Puntarenas', '14', 'ACAPULCO'),
  ('06', 'Puntarenas', '01', 'Puntarenas', '15', 'EL ROBLE'),
  ('06', 'Puntarenas', '01', 'Puntarenas', '16', 'ARANCIBIA'),
  ('06', 'Puntarenas', '02', 'Esparza', '01', 'ESPÍRITU SANTO'),
  ('06', 'Puntarenas', '02', 'Esparza', '02', 'SAN JUAN GRANDE'),
  ('06', 'Puntarenas', '02', 'Esparza', '03', 'MACACONA'),
  ('06', 'Puntarenas', '02', 'Esparza', '04', 'SAN RAFAEL'),
  ('06', 'Puntarenas', '02', 'Esparza', '05', 'SAN JERÓNIMO'),
  ('06', 'Puntarenas', '02', 'Esparza', '06', 'CALDERA'),
  ('06', 'Puntarenas', '03', 'Buenos Aires', '01', 'BUENOS AIRES'),
  ('06', 'Puntarenas', '03', 'Buenos Aires', '02', 'VOLCÁN'),
  ('06', 'Puntarenas', '03', 'Buenos Aires', '03', 'POTRERO GRANDE'),
  ('06', 'Puntarenas', '03', 'Buenos Aires', '04', 'BORUCA'),
  ('06', 'Puntarenas', '03', 'Buenos Aires', '05', 'PILAS'),
  ('06', 'Puntarenas', '03', 'Buenos Aires', '06', 'COLINAS'),
  ('06', 'Puntarenas', '03', 'Buenos Aires', '07', 'CHÁNGUENA'),
  ('06', 'Puntarenas', '03', 'Buenos Aires', '08', 'BIOLLEY'),
  ('06', 'Puntarenas', '03', 'Buenos Aires', '09', 'BRUNKA'),
  ('06', 'Puntarenas', '04', 'Montes de Oro', '01', 'MIRAMAR'),
  ('06', 'Puntarenas', '04', 'Montes de Oro', '02', 'LA UNIÓN'),
  ('06', 'Puntarenas', '04', 'Montes de Oro', '03', 'SAN ISIDRO'),
  ('06', 'Puntarenas', '05', 'Osa', '01', 'PUERTO CORTÉS'),
  ('06', 'Puntarenas', '05', 'Osa', '02', 'PALMAR'),
  ('06', 'Puntarenas', '05', 'Osa', '03', 'SIERPE'),
  ('06', 'Puntarenas', '05', 'Osa', '04', 'BAHÍA BALLENA'),
  ('06', 'Puntarenas', '05', 'Osa', '05', 'PIEDRAS BLANCAS'),
  ('06', 'Puntarenas', '05', 'Osa', '06', 'BAHÍA DRAKE'),
  ('06', 'Puntarenas', '06', 'Aguirre', '01', 'QUEPOS'),
  ('06', 'Puntarenas', '06', 'Aguirre', '02', 'SAVEGRE'),
  ('06', 'Puntarenas', '06', 'Aguirre', '03', 'NARANJITO'),
  ('06', 'Puntarenas', '07', 'Golfito', '01', 'GOLFITO'),
  ('06', 'Puntarenas', '07', 'Golfito', '02', 'PUERTO JIMÉNEZ'),
  ('06', 'Puntarenas', '07', 'Golfito', '03', 'GUAYCARÁ'),
  ('06', 'Puntarenas', '07', 'Golfito', '04', 'PAVÓN'),
  ('06', 'Puntarenas', '08', 'Coto Brus', '01', 'SAN VITO'),
  ('06', 'Puntarenas', '08', 'Coto Brus', '02', 'SABALITO'),
  ('06', 'Puntarenas', '08', 'Coto Brus', '03', 'AGUABUENA'),
  ('06', 'Puntarenas', '08', 'Coto Brus', '04', 'LIMONCITO'),
  ('06', 'Puntarenas', '08', 'Coto Brus', '05', 'PITTIER'),
  ('06', 'Puntarenas', '08', 'Coto Brus', '06', 'GUTIERREZ BRAUN'),
  ('06', 'Puntarenas', '09', 'Parrita', '01', 'PARRITA'),
  ('06', 'Puntarenas', '10', 'Corredores', '01', 'CORREDOR'),
  ('06', 'Puntarenas', '10', 'Corredores', '02', 'LA CUESTA'),
  ('06', 'Puntarenas', '10', 'Corredores', '03', 'CANOAS'),
  ('06', 'Puntarenas', '10', 'Corredores', '04', 'LAUREL'),
  ('06', 'Puntarenas', '11', 'Garabito', '01', 'JACÓ'),
  ('06', 'Puntarenas', '11', 'Garabito', '02', 'TÁRCOLES'),
  ('07', 'Limón', '01', 'Limón', '01', 'LIMÓN'),
  ('07', 'Limón', '01', 'Limón', '02', 'VALLE LA ESTRELLA'),
  ('07', 'Limón', '01', 'Limón', '04', 'MATAMA'),
  ('07', 'Limón', '02', 'Pococí', '01', 'GUÁPILES'),
  ('07', 'Limón', '02', 'Pococí', '02', 'JIMÉNEZ'),
  ('07', 'Limón', '02', 'Pococí', '03', 'RITA'),
  ('07', 'Limón', '02', 'Pococí', '04', 'ROXANA'),
  ('07', 'Limón', '02', 'Pococí', '05', 'CARIARI'),
  ('07', 'Limón', '02', 'Pococí', '06', 'COLORADO'),
  ('07', 'Limón', '02', 'Pococí', '07', 'LA COLONIA'),
  ('07', 'Limón', '03', 'Siquirres', '01', 'SIQUIRRES'),
  ('07', 'Limón', '03', 'Siquirres', '02', 'PACUARITO'),
  ('07', 'Limón', '03', 'Siquirres', '03', 'FLORIDA'),
  ('07', 'Limón', '03', 'Siquirres', '04', 'GERMANIA'),
  ('07', 'Limón', '03', 'Siquirres', '05', 'EL CAIRO'),
  ('07', 'Limón', '03', 'Siquirres', '06', 'ALEGRÍA'),
  ('07', 'Limón', '04', 'Talamanca', '01', 'BRATSI'),
  ('07', 'Limón', '04', 'Talamanca', '02', 'SIXAOLA'),
  ('07', 'Limón', '04', 'Talamanca', '03', 'CAHUITA'),
  ('07', 'Limón', '04', 'Talamanca', '04', 'TELIRE'),
  ('07', 'Limón', '05', 'Matina', '01', 'MATINA'),
  ('07', 'Limón', '05', 'Matina', '02', 'BATÁN'),
  ('07', 'Limón', '05', 'Matina', '03', 'CARRANDI'),
  ('07', 'Limón', '06', 'Guácimo', '01', 'GUÁCIMO'),
  ('07', 'Limón', '06', 'Guácimo', '02', 'MERCEDES'),
  ('07', 'Limón', '06', 'Guácimo', '03', 'POCORA'),
  ('07', 'Limón', '06', 'Guácimo', '04', 'RÍO JIMÉNEZ'),
  ('07', 'Limón', '06', 'Guácimo', '05', 'DUACARÍ')
)
insert into public.districts (canton_id, district_code, district_name, is_active)
select canton.canton_id, source_data.district_code, source_data.district_name, true
from source_data
cross join country
join public.provinces as province
  on province.country_id = country.country_id
 and province.province_name = source_data.province_name
join public.cantons as canton
  on canton.province_id = province.province_id
 and canton.canton_name = source_data.canton_name
on conflict (canton_id, district_name) do update
set district_code = excluded.district_code,
    is_active = excluded.is_active,
    updated_at = now();

commit;
