import { RiArrowDownSFill, RiArrowLeftSLine, RiArrowRightSFill, RiDownloadFill, RiExportFill, RiEyeFill, RiSearchLine } from "react-icons/ri";
import { ORDER_PAYMENT_CONFIG, ORDER_STATUS_CONFIG, OrderPaginationButton, OrderStatusBadge, formatOrderCurrency, formatOrderDate } from "./OrdersViewHelpers.jsx";

export default function OrdersList({ orders, filteredOrders, loading, onView, onClear }) {
  return <div className="mb-4 overflow-hidden rounded-xl border border-[#2a3550] bg-[#141d2e]">
    <div className="flex items-center justify-between border-b border-[#2a3550] px-5 py-3"><h3 className="text-sm font-semibold text-white">Listado de ordenes de venta</h3><button type="button" className="flex cursor-pointer items-center gap-1.5 text-xs text-gray-400 transition-colors hover:text-white"><RiExportFill size={13}/> Exportar <RiArrowDownSFill size={12}/></button></div>
    <table className="hidden w-full text-left lg:table"><thead><tr className="border-b border-[#2a3550]">{["Orden","Cliente","Fecha","Proxima fecha de pago","Total","Produccion","Pago","Vendedor","Acciones"].map(label=><th key={label} className={`px-4 py-3 text-[10px] font-semibold uppercase tracking-wider text-gray-500 ${label === "Acciones" ? "text-right" : ""}`}>{label}</th>)}</tr></thead><tbody className="divide-y divide-[#2a3550]">{filteredOrders.map(order=><tr key={order.id} className="transition-colors hover:bg-[#1c2538]/50"><td className="px-4 py-3 font-mono text-sm text-gray-300">{order.code}</td><td className="px-4 py-3 text-sm text-white">{order.client}</td><td className="px-4 py-3 text-sm text-gray-400">{formatOrderDate(order.createdAt)}</td><td className="px-4 py-3 text-sm text-gray-400">{formatOrderDate(order.nextPaymentDate)}</td><td className="px-4 py-3 text-sm font-semibold text-white">{formatOrderCurrency(order.total)}</td><td className="px-4 py-3"><OrderStatusBadge status={order.productionStatus} label={order.productionStatusLabel} config={ORDER_STATUS_CONFIG}/></td><td className="px-4 py-3"><OrderStatusBadge status={order.paymentStatus} label={order.paymentStatusLabel} config={ORDER_PAYMENT_CONFIG}/></td><td className="px-4 py-3"><div className="flex items-center gap-2"><div className="flex h-6 w-6 items-center justify-center rounded-full bg-[#C9A227]/15 text-[10px] font-bold text-[#C9A227]">{order.avatar}</div><span className="text-sm text-gray-300">{order.agent}</span></div></td><td className="px-4 py-3"><div className="flex items-center justify-end gap-0.5"><button type="button" onClick={()=>onView(order)} title="Ver" className="flex h-7 w-7 cursor-pointer items-center justify-center rounded-lg text-gray-400 hover:bg-[#C9A227]/15 hover:text-white"><RiEyeFill size={13}/></button><button type="button" title="Descargar" className="flex h-7 w-7 cursor-pointer items-center justify-center rounded-lg text-gray-400 hover:bg-[#C9A227]/15 hover:text-white"><RiDownloadFill size={13}/></button></div></td></tr>)}</tbody></table>
    {!loading && filteredOrders.length > 0 && <div className="divide-y divide-[#2a3550] lg:hidden">{filteredOrders.map(order=><button key={order.id} type="button" onClick={()=>onView(order)} className="block w-full p-4 text-left transition-colors hover:bg-[#1c2538]/60"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-white">{order.client}</p><p className="mt-1 font-mono text-xs text-gray-400">{order.code}</p></div><p className="whitespace-nowrap text-sm font-bold text-white">{formatOrderCurrency(order.total)}</p></div><div className="mt-3 grid grid-cols-2 gap-3 text-xs"><div><p className="text-gray-500">Fecha</p><p className="mt-1 text-gray-300">{formatOrderDate(order.createdAt)}</p></div><div><p className="text-gray-500">Próximo pago</p><p className="mt-1 text-gray-300">{formatOrderDate(order.nextPaymentDate)}</p></div></div><div className="mt-3 flex flex-wrap items-center gap-2"><OrderStatusBadge status={order.productionStatus} label={order.productionStatusLabel} config={ORDER_STATUS_CONFIG}/><OrderStatusBadge status={order.paymentStatus} label={order.paymentStatusLabel} config={ORDER_PAYMENT_CONFIG}/></div></button>)}</div>}
    {loading && <div className="flex flex-col items-center justify-center gap-3 py-14"><p className="text-sm text-gray-500">Cargando ordenes de venta...</p></div>}
    {!loading && filteredOrders.length === 0 && <div className="flex flex-col items-center justify-center gap-3 py-14"><RiSearchLine size={28} className="text-gray-600"/><p className="text-sm text-gray-500">No se encontraron ordenes de venta pendientes de pago o con pago adelantado</p><button type="button" onClick={onClear} className="cursor-pointer text-xs text-[#C9A227] hover:underline">Limpiar filtros</button></div>}
    <div className="flex flex-wrap items-center justify-between gap-3 border-t border-[#2a3550] px-4 py-3 sm:px-5"><span className="text-xs text-gray-500">Mostrando {filteredOrders.length} de {orders.length} ordenes</span><div className="flex items-center gap-1"><OrderPaginationButton icon={<RiArrowLeftSLine size={14}/>}/><OrderPaginationButton label={1} active/><OrderPaginationButton icon={<RiArrowRightSFill size={14}/>}/></div></div>
  </div>;
}
