/* eslint-disable react-refresh/only-export-components */
import { RiBarChartFill, RiCheckboxCircleFill, RiDeleteBinFill, RiFileListFill, RiKey2Fill, RiTeamFill, RiUserAddFill } from "react-icons/ri";

export function AdminFormField({ label, placeholder, value, onChange, type = "text", icon }) { return <div><label className="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-gray-300">{label}</label><div className="relative">{icon && <span className="absolute left-3 top-1/2 -translate-y-1/2 text-base leading-none">{icon}</span>}<input type={type} placeholder={placeholder} value={value} onChange={(event)=>onChange(event.target.value)} className={`w-full rounded-lg border border-[#2a3550] bg-[#222e44] py-2.5 pr-3 text-sm text-white outline-none placeholder:text-gray-400 focus:border-[#C9A227] ${icon?"pl-9":"pl-3"}`} /></div></div>; }
export function AdminToggle({ checked, onChange }) { return <button type="button" onClick={()=>onChange(!checked)} className={`relative h-5 w-10 shrink-0 rounded-full transition-colors ${checked?"bg-[#C9A227]":"bg-[#2a3448]"}`}><span className={`absolute top-0.5 h-4 w-4 rounded-full bg-white shadow transition-all ${checked?"left-5":"left-0.5"}`} /></button>; }
export function AdminActivityIcon({ type }) { const map={ login:[RiKey2Fill,"bg-[#C9A227]/15 text-[#C9A227]"], quote:[RiFileListFill,"bg-[#2d1b4e] text-[#c084fc]"], client:[RiTeamFill,"bg-[#1a2e1a] text-[#4ade80]"], sale:[RiBarChartFill,"bg-[#C9A227]/15 text-[#C9A227]"], report:[RiBarChartFill,"bg-[#2d200a] text-[#fbbf24]"], delete:[RiDeleteBinFill,"bg-[#3b1a1a] text-[#f87171]"], export:[RiFileListFill,"bg-[#1a2e1a] text-[#4ade80]"], create:[RiUserAddFill,"bg-[#C9A227]/15 text-[#C9A227]"], approve:[RiCheckboxCircleFill,"bg-[#14301a] text-[#4ade80]"] }; const [Icon,color]=map[type]||map.login; return <div className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full ${color}`}><Icon size={12} /></div>; }

export function generateTemporaryPassword() { return `GV-${Math.random().toString(36).slice(2,10)}${Math.floor(100+Math.random()*900)}!`; }
export function getEmptyAdminUserForm() { return { name:"", email:"", phone:"", companies:[], departmentId:"", role:"", password:generateTemporaryPassword(), status:"Activo" }; }
export function splitAdminFullName(fullName) { const [name,...surnameParts]=fullName.trim().split(/\s+/).filter(Boolean); return { name:name||"", surname:surnameParts.join(" ") }; }
const ROLE_BADGES=["bg-[#C9A227]/15 text-[#C9A227]","bg-[#2d1b4e] text-[#c084fc]","bg-[#1a2e1a] text-[#4ade80]","bg-[#2d200a] text-[#fbbf24]","bg-[#3b1a1a] text-[#f87171]","bg-[#0f2d3a] text-[#60a5fa]"];
export function mapAdminRoleRow(role,index) { return { id:role.role_id, name:role.role_name||"Sin nombre", code:role.role_code||"", description:role.description||"", isActive:role.is_active!==false, status:role.is_active===false?"Inactivo":"Activo", badge:ROLE_BADGES[index%ROLE_BADGES.length] }; }
