import { RiArrowDownSFill, RiCalendarLine, RiFilterLine, RiSearchLine, RiTimeLine } from "react-icons/ri";
import { AdminActivityIcon } from "./AdminViewHelpers.jsx";

const ACTIVITY_GROUPS = [
  { id:1, group:"Hoy", items:[["José González","JG","#C9A227","inició sesión","Hace 10 minutos","login"],["María Castillo","MC","#ec4899","creó una cotización","Hace 35 minutos","quote"],["Luis Pérez","LP","#6366f1","actualizó un cliente","Hace 1 hora","client"],["Ana Córdoba","AC","#f59e0b","generó un reporte financiero","Hace 2 horas","report"]] },
  { id:2, group:"Ayer", items:[["Ana Córdoba","AC","#f59e0b","modificó una venta","23 Jun - 4:15 PM","sale"],["Roberto Sánchez","RS","#ef4444","eliminó una cotización","23 Jun - 2:30 PM","delete"],["Daniela Cruz","DC","#22c55e","exportó lista de clientes","23 Jun - 11:00 AM","export"]] },
  { id:3, group:"22 Jun", items:[["José González","JG","#C9A227","creó un nuevo usuario","22 Jun - 9:45 AM","create"],["María Castillo","MC","#ec4899","aprobó una orden de compra","22 Jun - 8:20 AM","approve"]] },
].map((group)=>({ ...group, items:group.items.map(([user,initials,color,action,time,icon])=>({user,initials,color,action,time,icon})) }));

export default function AdminActivityTab({ search, type, onSearchChange, onTypeChange }) {
  const query = search.trim().toLowerCase();
  const groups = ACTIVITY_GROUPS.map((group)=>({ ...group, items:group.items.filter((item)=>(!query || `${item.user} ${item.action}`.toLowerCase().includes(query)) && (type==="Todos" || item.icon===type)) })).filter((group)=>group.items.length);
  return <section><div className="mb-6 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><RiSearchLine size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" /><input value={search} onChange={(event)=>onSearchChange(event.target.value)} placeholder="Buscar usuario..." className="w-full rounded-lg border border-[#2a3550] bg-[#222e44] py-2 pl-9 pr-3 text-sm text-white outline-none focus:border-[#C9A227]" /></label><label className="relative"><RiFilterLine size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" /><select value={type} onChange={(event)=>onTypeChange(event.target.value)} className="min-w-[180px] appearance-none rounded-lg border border-[#2a3550] bg-[#222e44] py-2 pl-9 pr-8 text-sm text-gray-300 outline-none focus:border-[#C9A227]"><option value="Todos">Todos los tipos</option><option value="login">Inicios de sesión</option><option value="sale">Ventas</option><option value="quote">Cotizaciones</option><option value="client">Clientes</option></select><RiArrowDownSFill size={15} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-gray-500" /></label><label className="relative"><RiCalendarLine size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" /><input type="date" className="rounded-lg border border-[#2a3550] bg-[#222e44] py-2 pl-9 pr-3 text-sm text-gray-300 outline-none focus:border-[#C9A227]" /></label></div><div className="space-y-6">{groups.map((group)=><div key={group.id}><div className="mb-3 flex items-center gap-3"><span className="text-xs font-semibold uppercase tracking-wider text-gray-300">{group.group}</span><div className="h-px flex-1 bg-[#2a3550]" /></div><div className="overflow-hidden rounded-xl border border-[#2a3550] bg-[#141d2e]">{group.items.map((item,index)=><div key={`${item.user}-${item.time}`} className={`flex items-start gap-4 px-5 py-4 transition-colors hover:bg-[#1c2538] ${index<group.items.length-1?"border-b border-[#2a3550]":""}`}><div className="relative mt-0.5"><div className="flex h-8 w-8 items-center justify-center rounded-full text-xs font-bold text-white" style={{backgroundColor:item.color}}>{item.initials}</div><AdminActivityIcon type={item.icon} /></div><div className="min-w-0 flex-1"><p className="text-sm text-white"><strong>{item.user}</strong><span className="text-gray-400"> {item.action}</span></p><p className="mt-0.5 flex items-center gap-1 text-xs text-gray-600"><RiTimeLine size={11}/>{item.time}</p></div></div>)}</div></div>)}</div></section>;
}
