import { RiArrowDownSFill, RiCheckLine, RiLockPasswordFill, RiSmartphoneFill, RiTimerLine } from "react-icons/ri";
import { AdminToggle } from "./AdminViewHelpers.jsx";

const GROUPS=[
  { title:"Políticas de Contraseña", icon:RiLockPasswordFill, color:"text-[#C9A227]", items:[["strongPassword","Requerir contraseña fuerte","Mínimo 8 caracteres, mayúsculas, números y símbolos."],["forceChange90","Forzar cambio cada 90 días","Los usuarios deberán actualizar su contraseña periódicamente."],["lockAfterFail","Bloquear después de 5 intentos fallidos","La cuenta se bloqueará automáticamente al superar el límite."]] },
  { title:"Autenticación", icon:RiSmartphoneFill, color:"text-[#c084fc]", items:[["twoFactor","Habilitar doble factor (2FA)","Requiere un segundo método de verificación al iniciar sesión."],["googleLogin","Permitir inicio de sesión con Google","Los usuarios podrán autenticarse usando su cuenta de Google."],["autoLogout","Cierre automático por inactividad","La sesión se cerrará automáticamente al no detectar actividad."]] },
];

export default function AdminSecurityTab({ security, onChange }) { return <section className="max-w-2xl space-y-4">{GROUPS.map(({title,icon:Icon,color,items})=><div key={title} className="overflow-hidden rounded-xl border border-[#2a3550] bg-[#141d2e]"><header className="flex items-center gap-2 border-b border-[#2a3550] px-5 py-4"><Icon size={16} className={color}/><h3 className="text-sm font-semibold text-white">{title}</h3></header><div className="divide-y divide-[#2a3550]">{items.map(([key,label,description])=><div key={key} className="flex items-center justify-between gap-4 px-5 py-4 transition-colors hover:bg-[#1c2538]"><div><p className="text-sm font-medium text-white">{label}</p><p className="mt-0.5 text-xs text-gray-500">{description}</p></div><AdminToggle checked={security[key]} onChange={(value)=>onChange(key,value)} /></div>)}</div></div>)}<div className="overflow-hidden rounded-xl border border-[#2a3550] bg-[#141d2e]"><header className="flex items-center gap-2 border-b border-[#2a3550] px-5 py-4"><RiTimerLine size={16} className="text-[#4ade80]"/><h3 className="text-sm font-semibold text-white">Sesión</h3></header><div className="flex items-center justify-between gap-4 px-5 py-4"><div><p className="text-sm font-medium text-white">Tiempo máximo de sesión</p><p className="mt-0.5 text-xs text-gray-500">La sesión se cerrará después del tiempo seleccionado.</p></div><label className="relative"><select value={security.sessionTime} onChange={(event)=>onChange("sessionTime",event.target.value)} className="appearance-none rounded-lg border border-[#2a3550] bg-[#222e44] py-2 pl-3 pr-8 text-sm text-white outline-none focus:border-[#C9A227]"><option value="15">15 minutos</option><option value="30">30 minutos</option><option value="60">1 hora</option><option value="120">2 horas</option><option value="480">8 horas</option></select><RiArrowDownSFill size={15} className="pointer-events-none absolute right-2 top-1/2 -translate-y-1/2 text-gray-500"/></label></div></div><button type="button" className="flex items-center gap-2 rounded-lg bg-[#C9A227] px-5 py-2.5 text-sm font-medium text-white hover:bg-[#B8921F]"><RiCheckLine size={16}/>Guardar Configuración</button></section>; }
