import { RiArrowDownSFill, RiExportFill, RiEyeFill, RiSearchLine } from "react-icons/ri";
import SalesStatusBadge from "./SalesStatusBadge.jsx";
import { SALES_PAYMENT_CONFIG, formatSalesCurrency, formatSalesDate } from "./salesViewConfig.js";

export default function SalesList({ sales, totalSales, loading, onClear, onView }) {
  return (
    <section className="mb-4 overflow-hidden rounded-xl border border-[#2a3550] bg-[#141d2e]">
      <div className="flex items-center justify-between border-b border-[#2a3550] px-5 py-3"><h2 className="text-sm font-semibold text-white">Listado de Ventas</h2><button type="button" className="flex items-center gap-1.5 text-xs text-gray-400 transition-colors hover:text-white"><RiExportFill size={13} />Exportar<RiArrowDownSFill size={12} /></button></div>
      <table className="hidden w-full text-left lg:table"><thead><tr className="border-b border-[#2a3550]">{["Orden", "Fecha de venta", "Cliente", "Método de pago", "Condición de pago", "Estado de pago", "Total", "Saldo pendiente", "Responsable", "Acciones"].map((header) => <th key={header} className="px-4 py-3 text-[10px] font-semibold uppercase tracking-wider text-gray-500 last:text-right">{header}</th>)}</tr></thead><tbody className="divide-y divide-[#2a3550]">{sales.map((sale) => <tr key={sale.id} onClick={() => onView(sale)} className="cursor-pointer transition-colors hover:bg-[#1c2538]/50"><td className="px-4 py-3 font-mono text-sm text-gray-300">{sale.code}</td><td className="px-4 py-3 text-sm text-gray-400">{formatSalesDate(sale.saleDate)}</td><td className="px-4 py-3 text-sm text-white">{sale.client}</td><td className="px-4 py-3 text-sm text-gray-300">{sale.paymentMethod}</td><td className="px-4 py-3 text-sm text-gray-300">{sale.paymentCondition}</td><td className="px-4 py-3"><SalesStatusBadge status={sale.paymentStatus} label={sale.paymentStatusLabel} config={SALES_PAYMENT_CONFIG} /></td><td className="px-4 py-3 text-sm font-semibold text-white">{formatSalesCurrency(sale.total)}</td><td className="px-4 py-3 text-sm font-semibold text-gray-300">{formatSalesCurrency(sale.balance)}</td><td className="px-4 py-3"><div className="flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-[#C9A227]/15 text-[10px] font-bold text-[#C9A227]">{sale.avatar}</span><span className="text-sm text-gray-300">{sale.representative}</span></div></td><td className="px-4 py-3 text-right"><button type="button" onClick={(event) => { event.stopPropagation(); onView(sale); }} className="inline-flex h-7 w-7 items-center justify-center rounded-lg text-gray-400 transition-colors hover:bg-[#C9A227]/15 hover:text-white" title="Ver"><RiEyeFill size={13} /></button></td></tr>)}</tbody></table>
      {!loading && sales.length > 0 && <div className="divide-y divide-[#2a3550] lg:hidden">{sales.map((sale) => <button key={sale.id} type="button" onClick={() => onView(sale)} className="block w-full p-4 text-left transition-colors hover:bg-[#1c2538]/60"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-white">{sale.client}</p><p className="mt-1 font-mono text-xs text-gray-400">{sale.code}</p></div><p className="whitespace-nowrap text-sm font-bold text-white">{formatSalesCurrency(sale.total)}</p></div><div className="mt-3 grid grid-cols-2 gap-3 text-xs"><div><p className="text-gray-500">Fecha de venta</p><p className="mt-1 text-gray-300">{formatSalesDate(sale.saleDate)}</p></div><div><p className="text-gray-500">Método de pago</p><p className="mt-1 truncate text-gray-300">{sale.paymentMethod}</p></div><div><p className="text-gray-500">Condición de pago</p><p className="mt-1 truncate text-gray-300">{sale.paymentCondition}</p></div><div><p className="text-gray-500">Saldo pendiente</p><p className="mt-1 text-gray-300">{formatSalesCurrency(sale.balance)}</p></div></div><div className="mt-3 flex flex-wrap gap-2"><SalesStatusBadge status={sale.paymentStatus} label={sale.paymentStatusLabel} config={SALES_PAYMENT_CONFIG} /></div><p className="mt-3 text-xs text-gray-400">Responsable: {sale.representative}</p></button>)}</div>}
      {loading && <div className="py-14 text-center text-sm text-gray-500">Cargando ventas...</div>}
      {!loading && sales.length === 0 && <div className="flex flex-col items-center gap-3 py-14"><RiSearchLine size={28} className="text-gray-600" /><p className="text-sm text-gray-500">No se encontraron ventas registradas.</p><button type="button" onClick={onClear} className="text-xs text-[#C9A227] hover:underline">Limpiar filtros</button></div>}
      <footer className="border-t border-[#2a3550] px-5 py-3 text-xs text-gray-500">Mostrando {sales.length} de {totalSales} ventas</footer>
    </section>
  );
}
